#! /bin/sh

## STARTUP ##

# Start or reload sxhkd
pgrep -x sxhkd > /dev/null && pkill -USR1 -x sxhkd > /dev/null || sxhkd &

# Start keyboard layout catcher
gxkb &

# Start notifications daemon
dunst &

# Start picom (compton) compositor
picom --config /home/ian/.config/picom/picom.conf -b

# Use wallpaper
feh --bg-fill /home/ian/Pictures/wallpaper.jpg

# Launch polybar
$HOME/.config/polybar/launch.sh

## CONFIG ##

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           1

# bspc config normal_border_color  "#808080"
# bspc config active_border_color  "#4A4A4A"
# bspc config focused_border_color "#808080"

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc rule -a Emacs desktop='^1' state=fullscreen
bspc rule -a Chromium desktop='^3' follow=on
bspc rule -a Slack desktop='^4' state=floating follow=on
bspc rule -a Bitwarden desktop='^5' state=floating follow=on
bspc rule -a zoom desktop='^6' state=floating follow=on
