#! /bin/sh

## STARTUP ##

# Start or reload sxhkd
pgrep -x sxhkd > /dev/null && pkill -USR1 -x sxhkd > /dev/null || sxhkd &

# Start keyboard layout catcher
gxkb &

# Start notifications daemon
dunst &

# Start picom (compton) compositor
# Commenting: it is using CPU and Memory
# picom --config /home/ian/.config/picom/picom.conf -b

# Use wallpaper
feh --bg-fill /home/ian/Pictures/wallpaper.png

# Launch polybar
#$HOME/.config/polybar/launch.sh

# Launch Tint2
tint2 &

## CONFIG ##

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9 0

# xrandr --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal

bspc config border_width         1
bspc config window_gap           1

# bspc config normal_border_color  "#808080"
# bspc config active_border_color  "#4A4A4A"
# bspc config focused_border_color "#808080"

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

# use: xprop | grep WM_CLASS
bspc rule -a Emacs desktop='^1' state=fullscreen
bspc rule -a Chromium desktop='^3' follow=on
bspc rule -a Slack desktop='^4' state=tiled follow=on
bspc rule -a Bitwarden desktop='^5' rectangle='1000x800+200+100' state=floating follow=on
bspc rule -a Keybase desktop='^5' rectangle='1000x800+400+130' state=floating follow=on
bspc rule -a 1Password desktop='^5' rectangle='1000x800+600+160' state=floating follow=on
bspc rule -a zoom desktop='^6' state=floating follow=on
bspc rule -a Telegram desktop='^7' state=floating follow=on
bspc rule -a pinentry-qt state=floating follow=on

