#! /bin/sh

## STARTUP ##

# Start or reload sxhkd
pgrep -x sxhkd > /dev/null && pkill -USR1 -x sxhkd > /dev/null || sxhkd &

# Start keyboard layout catcher
gxkb &

# Start notifications daemon
dunst &

# Launch polybar
$HOME/.config/polybar/launch.sh

## CONFIG ##

bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           2

bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc rule -a Emacs desktop='^1' state=fullscreen
bspc rule -a Chromium desktop='^3'
bspc rule -a Slack desktop='^4' state=floating follow=on
bspc rule -a Zoom desktop='^6' state=floating follow=on
